import data from '../data/battleEncounters.json';
import mapsData from '../data/battleMaps.json';
import { FLEET_MAX, GameState, fleetShips, shipTypeById } from '../state';
import type { BattleMapDefinition, BattleUnit, CannonTypeId, Facing, ShipSize, Side } from './battleTypes';
import { deploymentHexes } from './battleRules';

type Kind = 'pirate'|'quest'|'story'|'mate'; type Row=[string,number,number,CannonTypeId?,string?]; type Encounter={id:string;kind:Kind;tier:number;mapId:string;loot:number;countWeights?:[number,number][];ships?:Row[];fixedShips?:Row[];matchNames?:string[];storyAllies?:Row[]};
const rows=(data as unknown as {encounters:Encounter[]}).encounters; const maps=(mapsData as {maps:BattleMapDefinition[]}).maps;
export interface HexBattleRequest {kind:Kind;tier?:number;questCombat?:boolean;mateDuelId?:string;storyDuelChapterId?:string;duelName?:string;}
export interface HexBattleLaunchData {mapId:string;seed:number;units:BattleUnit[];unitNames:Record<string,string>;request:HexBattleRequest;encounterId:string;loot:number;playerShipIndexes:Record<string,number>;}
const rand=(seed:number)=>{let v=seed>>>0;v^=v<<13;v^=v>>>17;v^=v<<5;return(v>>>0)/4294967296;};
const size=(id:string):ShipSize=>shipTypeById(id).hullMax>=180?'large':shipTypeById(id).hullMax>=120?'medium':'small';
function unit(side:Side,id:string,row:Row,hex:BattleUnit['hex'],flagship:boolean):BattleUnit {const [typeId,cannons,crew,cannonTypeId='standard']=row,t=shipTypeById(typeId);return{id,side,shipTypeId:typeId,shipSize:size(typeId),flagship,hex:{...hex},facing:(side==='player'?0:3)as Facing,hull:t.hullMax,hullMax:t.hullMax,cannons:Math.min(cannons,t.cannonSlots),cannonTypeId,cannonPower:1,gunnerMod:1,armorMultiplier:1,crew,boardingBonus:0,crewLossMultiplier:1,movePoints:size(typeId)==='small'?4:size(typeId)==='large'?2:3,moveSpent:0,moved:false,acted:false,repaired:false,status:'active'};}
/** P7 ????????????????tier???????????????? JSON ??? */
export function createHexBattleLaunch(state:GameState,request:HexBattleRequest,seed=state.day*1009+7):HexBattleLaunchData {const e=rows.find(x=>x.kind===request.kind&&x.matchNames?.includes(request.duelName??''))??rows.find(x=>x.kind===request.kind&&x.tier===(request.tier??1))??rows[0],map=maps.find(x=>x.id===e.mapId)??maps[0],ships=fleetShips(state).slice(0,FLEET_MAX),pc=deploymentHexes(map,'player'),ec=deploymentHexes(map,'enemy'),names:Record<string,string>={},indexes:Record<string,number>={},units:BattleUnit[]=[];ships.forEach((ship,i)=>{const id=`p${i}`;indexes[id]=i;names[id]=i?'????'+i:'????';const u=unit('player',id,[ship.typeId,ship.cannons,Math.max(1,Math.floor(state.crew/ships.length)),(ship.cannonType??'standard')as CannonTypeId],pc[i],i===0);u.hull=Math.max(1,Math.min(u.hullMax,ship.hull));units.push(u);});let count=e.fixedShips?.length??1;if(e.countWeights){let c=0;for(const[n,w]of e.countWeights){c+=w;if(rand(seed)<c){count=n;break;}}}(e.fixedShips??e.ships??[]).slice(0,count).forEach((r,i)=>{const id=`e${i}`;names[id]=r[4]??(i?'????'+i:'????');units.push(unit('enemy',id,r,ec[i],i===0));});(request.kind==='story'?e.storyAllies??[]:[]).slice(0,FLEET_MAX-ships.length).forEach((r,i)=>{const id=`a${i}`;names[id]=r[4]??'????';units.push(unit('player',id,r,pc[ships.length+i],false));});return{mapId:map.id,seed,units,unitNames:names,request,encounterId:e.id,loot:e.loot,playerShipIndexes:indexes};}
